import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Menu, Search, X, MapPin, Clock, DollarSign, Mountain, Users, BookOpen, Heart, Eye, Radio, Plus } from 'lucide-react';
import './style.css';

const places = [
  { id:'socotra', title:'Socotra Island', country:'Yemen', mood:'Alien Landscapes', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=85', class:'socotra', desc:'A floating garden of dragon blood trees, carved by wind and time.' },
  { id:'abandoned', title:'Kolmanskop', country:'Namibia', mood:'Lost & Abandoned', image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85', class:'abandoned', desc:'The desert is quietly reclaiming this once-luminous diamond town.' },
  { id:'pink', title:'Lake Hillier', country:'Australia', mood:'Unreal Colors', image:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=85', class:'pink', desc:'A bubblegum-pink lake beside an endless blue ocean.' },
  { id:'wild', title:'Dallol', country:'Ethiopia', mood:'Into the Wild', image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85', class:'wild', desc:'Sulfur springs and salt plains at one of Earth’s hottest places.' },
];
const moods = ['All places','Alien Landscapes','Lost & Abandoned','Unreal Colors','Into the Wild'];
const week = [{day:'MON',reads:1260},{day:'TUE',reads:1460},{day:'WED',reads:1860},{day:'THU',reads:1670},{day:'FRI',reads:2310},{day:'SAT',reads:2860},{day:'SUN',reads:2490}];
const activity = [['Maya R.','saved','The ghost ships of the Aral Sea','2 min ago'],['Tomas K.','started reading','Socotra Island','8 min ago'],['Nora E.','joined the atlas','—','16 min ago'],['Ariane B.','saved','Dallol: Earth’s acid garden','25 min ago'],['Theo L.','finished','Lake Hillier','41 min ago']];
const articles = [
 {title:'Inside the blue heart of an ice cave', place:'Vatnajökull, Iceland', mood:'Unreal Colors', time:'6 MIN READ', image:'https://images.unsplash.com/photo-1517783999520-f068d7431a60?auto=format&fit=crop&w=1200&q=85', excerpt:'Under Europe’s largest glacier, summer light finds a language of its own.'},
 {title:'Gunkanjima, the island that time forgot', place:'Nagasaki, Japan', mood:'Lost & Abandoned', time:'9 MIN READ', image:'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1200&q=85', excerpt:'A concrete city at sea, abandoned so suddenly that old calendars still turn to 1974.'},
 {title:'Following the wind into Patagonia', place:'Torres del Paine, Chile', mood:'Into the Wild', time:'7 MIN READ', image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=85', excerpt:'Where the weather writes the itinerary and every horizon feels newly discovered.'},
 {title:'The lake that blushes without apology', place:'Western Australia', mood:'Unreal Colors', time:'5 MIN READ', image:'https://images.unsplash.com/photo-1520962922320-2038eebab146?auto=format&fit=crop&w=1200&q=85', excerpt:'A strange pink ribbon in the scrublands, brighter than the sky beside it.'},
 {title:'The desert that swallowed a diamond town', place:'Kolmanskop, Namibia', mood:'Lost & Abandoned', time:'8 MIN READ', image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', excerpt:'Sand pours through Art Nouveau windows, erasing every trace of prosperity.'},
 {title:'A forest of dragon blood trees', place:'Socotra, Yemen', mood:'Alien Landscapes', time:'10 MIN READ', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85', excerpt:'This island has spent millions of years making its own rules for life.'},
 {title:'The sulphur garden at the edge of heat', place:'Dallol, Ethiopia', mood:'Alien Landscapes', time:'7 MIN READ', image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85', excerpt:'At the floor of a salt desert, colour erupts from a world still under construction.'}
];

function App(){
 const [active, setActive] = useState('All places'); const [selected, setSelected] = useState(null); const [menu, setMenu] = useState(false); const [page,setPage] = useState('home');
 const shown = active === 'All places' ? places : places.filter(p => p.mood === active);
 useEffect(()=>{ const close=e=> e.key==='Escape' && setSelected(null); window.addEventListener('keydown',close); return()=>window.removeEventListener('keydown',close);},[]);
 return <main>
  <nav><a className="brand" href="#top" onClick={()=>setPage('home')}><span>ATLAS</span> BEYOND THE MAP</a><div className="nav-links"><a href="#discover" onClick={()=>setPage('home')}>Discover</a><button className={page==='articles'?'nav-active':''} onClick={()=>{setPage('articles');setMenu(false);window.scrollTo(0,0)}}>Articles</button><a href="#journal" onClick={()=>setPage('home')}>Journal</a></div><button className="search"><Search size={18}/><span>Search the unknown</span><i>⌘ K</i></button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>
  {menu && <div className="mobile-nav"><a href="#discover" onClick={()=>setPage('home')}>Discover</a><button onClick={()=>{setPage('articles');setMenu(false)}}>Articles</button><a href="#journal" onClick={()=>setPage('home')}>Journal</a></div>}
  {page === 'articles' ? <ArticlesPage select={setSelected}/> : <>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span></span> WHERE THE WORLD GETS STRANGE</p><h1>GO BEYOND<br/>THE <em>ORDINARY.</em></h1><p className="intro">A field guide to the improbable corners of our planet. No city breaks. No bucket lists. Just places that shouldn’t quite exist.</p><a href="#discover" className="explore">EXPLORE THE ATLAS <ArrowUpRight size={18}/></a></div>
  <div className="globe-stage"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="glow"></div><div className="globe"><div className="continent c1"></div><div className="continent c2"></div><div className="continent c3"></div><div className="grid"></div>{places.map((p,i)=><button aria-label={p.title} key={p.id} className={'pin p'+i} onClick={()=>setSelected(p)}><b></b><span>{p.title}</span></button>)}</div><p className="rotate">DRAG TO ROTATE <span>↻</span></p></div>
  <div className="scroll"><span></span> SCROLL TO EXPLORE</div></section>
  <section className="moods" id="discover"><div><p className="eyebrow"><span></span> FOLLOW A FEELING</p><h2>CHOOSE YOUR <em>MOOD</em></h2></div><div className="mood-list">{moods.map((m,i)=><button key={m} className={active===m?'active':''} onClick={()=>setActive(m)}><small>0{i}</small>{m}<ArrowUpRight size={17}/></button>)}</div></section>
  <section className="stories" id="stories"><div className="section-head"><div><p className="eyebrow"><span></span> FIELD NOTES</p><h2>PLACES THAT<br/><em>REWRITE</em> THE MAP.</h2></div><a href="#all">VIEW ALL STORIES <ArrowUpRight size={17}/></a></div><div className="cards">{shown.map((p,i)=><article className={'card '+p.class} key={p.id} onClick={()=>setSelected(p)}><img src={p.image} alt=""/><div className="card-shade"></div><div className="card-top"><span>{p.mood}</span><b>0{i+1}</b></div><div className="card-bottom"><p>{p.country}</p><h3>{p.title}</h3><span className="read">READ STORY <ArrowUpRight size={16}/></span></div></article>)}</div></section>
  <WeekActivity />
  <section className="quote"><p>“The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.”</p><span>— MARCEL PROUST</span></section>
  <footer id="journal"><div className="brand"><span>ATLAS</span> BEYOND THE MAP</div><p>Made for the perpetually curious.</p><div><a href="#instagram">Instagram</a><a href="#contact">Contact</a></div></footer>
  </>}{selected&&<PlaceModal place={selected} close={()=>setSelected(null)}/>}</main>
}
function ArticlesPage({select}){const [filter,setFilter]=useState('All stories');const filters=['All stories','Alien Landscapes','Lost & Abandoned','Unreal Colors','Into the Wild']; const list=filter==='All stories'?articles:articles.filter(a=>a.mood===filter); return <><section className="articles-hero"><p className="eyebrow"><span></span> THE ATLAS LIBRARY</p><h1>STORIES FROM<br/>THE <em>EDGE.</em></h1><p>Seven field notes from places that live outside the usual itinerary. Follow the peculiar, the remote, and the quietly impossible.</p></section><section className="articles-page"><div className="article-filter">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'selected':''}>{f}</button>)}</div><div className="article-count"><span>ALL FIELD NOTES</span><b>{list.length.toString().padStart(2,'0')} STORIES</b></div><div className="article-grid">{list.map((a,i)=><article className={i===0?'feature-article':''} key={a.title} onClick={()=>select({...a,country:a.place,desc:a.excerpt})}><div className="article-img"><img src={a.image} alt=""/><span>{a.mood}</span></div><div className="article-text"><p>{a.place} <i>·</i> {a.time}</p><h2>{a.title}</h2><div className="article-bottom"><span>{a.excerpt}</span><b>READ FIELD NOTE <ArrowUpRight size={15}/></b></div></div></article>)}</div></section><footer><div className="brand"><span>ATLAS</span> BEYOND THE MAP</div><p>Made for the perpetually curious.</p><div><a href="#instagram">Instagram</a><a href="#contact">Contact</a></div></footer></>}
function WeekActivity(){ const max=Math.max(...week.map(d=>d.reads)); return <section className="week" id="journal"><div className="week-heading"><div><p className="eyebrow"><span></span> ATLAS PULSE</p><h2>A WEEK OF<br/><em>WANDERING.</em></h2></div><p>This is how the atlas came alive over the last seven days — new readers, fresh field notes, and routes saved for later.</p></div><div className="week-grid"><div className="stats-panel"><div className="period"><span><i></i> LIVE SIMULATION</span><small>12 — 18 AUG 2026</small></div><div className="stat-cards"><div><Users/><p>NEW WAYFINDERS</p><b>1,482</b><small>↑ 18.6% this week</small></div><div><BookOpen/><p>STORIES PUBLISHED</p><b>12</b><small>4 new regions mapped</small></div><div><Heart/><p>PLACES SAVED</p><b>3,667</b><small>↑ 24.1% this week</small></div></div><div className="chart-title"><span>READS THROUGH THE WEEK</span><b>13,910 <small>total</small></b></div><div className="chart">{week.map(d=><div className="bar-col" key={d.day}><div className="tooltip">{d.reads.toLocaleString()}</div><div className="bar" style={{height:`${d.reads/max*100}%`}}></div><small>{d.day}</small></div>)}</div></div><aside className="activity-panel"><div className="activity-title"><div><Radio size={15}/><span>HAPPENING NOW</span></div><b>26</b></div><div className="activity-list">{activity.map((a,i)=><div className="activity-row" key={a[0]}><div className={'avatar a'+i}>{a[0][0]}</div><p><strong>{a[0]}</strong> {a[1]}<br/>{a[2] !== '—' && <em>{a[2]}</em>}</p><time>{a[3]}</time></div>)}</div><button className="activity-more">VIEW ACTIVITY <ArrowUpRight size={15}/></button></aside></div><div className="published"><div><span className="eyebrow"><span></span> NEW THIS WEEK</span><h3>Fresh marks on<br/>the map.</h3></div><div className="published-list"><article><span>01</span><div><p>UNREAL COLORS · ICELAND</p><b>Inside the blue heart of an ice cave</b></div><Eye size={16}/></article><article><span>02</span><div><p>LOST & ABANDONED · JAPAN</p><b>Gunkanjima, the island that time forgot</b></div><Eye size={16}/></article><article><span>03</span><div><p>INTO THE WILD · CHILE</p><b>Following the wind into Patagonia</b></div><Eye size={16}/></article></div><button className="add-story"><Plus size={15}/> DISCOVER A NEW STORY</button></div></section>}
function PlaceModal({place,close}){ return <div className="modal" onClick={close}><article onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="modal-image" style={{backgroundImage:`url(${place.image})`}}><p className="eyebrow"><span></span> {place.mood.toUpperCase()}</p><h2>{place.title}</h2><p>{place.country}</p></div><div className="pass"><div><MapPin/> <small>COORDINATES</small><b>12.34° N / 53.67° E</b></div><div><Clock/><small>BEST TIME</small><b>OCT — APR</b></div><div><Mountain/><small>DIFFICULTY</small><b>CHALLENGING</b></div><div><DollarSign/><small>BUDGET</small><b>FROM $1,800</b></div></div><div className="modal-copy"><p className="eyebrow"><span></span> ONE MINUTE SNAPSHOT</p><p>{place.desc} This is the kind of destination that slips past ordinary itineraries and lingers long after you leave.</p><button>READ THE FULL STORY <ArrowUpRight size={16}/></button></div></article></div>}
createRoot(document.getElementById('root')).render(<App/>);
